<a href="https://colab.research.google.com/github/casjunior93/tensorflow-developer-certificate/blob/main/02_Numpy_e_tensores.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Introdução ao Numerical Python (Numpy)

## 1. O vetor n-dimensional (tensor)

O NumPy é uma biblioteca para a linguagem Python com funções para se trabalhar com computação numérica. Seu principal objeto é o vetor n-dimensional, ou ndarray. Um vetor n-dimensional também é conhecido pelo nome tensor. A principal característica do ndarray é que ele deve ser homogêneo, ou seja, diferentemente do objeto lista, todos os seus elementos devem ser do mesmo tipo. [(3)](http://www.opl.ufc.br/post/numpy/)

## 2. Criando tensores com numpy

Criando um ndarray com numpy

### 2.1 Vetor (tensor 1-dimensional)

In [2]:
import numpy as np

In [4]:
vetor = np.array([1,2,3,4])
vetor

array([1, 2, 3, 4])

In [6]:
print(f'Um vetor tem {vetor.ndim} dimensão.')

Um vetor tem 1 dimensão.


Tipos dos elementos de um tensor

In [7]:
vetor.dtype

dtype('int64')

Neste caso, ao criar o vetor, o tipo default assumido foi int64, mas o tipo desejado pode ser especificado na criação do tensor.

In [8]:
vetor = np.array([1,2,3,4], dtype='float64')
vetor.dtype

dtype('float64')

Ao criar um tensor com um float, os elementos do tensor automaticamente serão do tipo float. Os elementos ficam com o mesmo tipo float64.

In [9]:
vetor = np.array([1,2.,3])
vetor.dtype

dtype('float64')

Forma do tensor

In [10]:
vetor.shape

(3,)

O vetor tem 1 dimensão e 4 elementos.

### 2.2 Criando uma matriz (tensor 2-dimensional)

In [12]:
matriz = np.array([
    [1,2,3],
    [4,5,6]
])
matriz

array([[1, 2, 3],
       [4, 5, 6]])

In [16]:
print(f'Dimensão: {matriz.ndim}-dimensional')
print(f'Forma: {matriz.shape}')

Dimensão: 2-dimensional
Forma: (2, 3)


Criando uma matriz com .shape

In [22]:
vetor = np.array([1,2,3,4,5,6,7,8,9])
vetor.shape = (3,3)

In [23]:
matriz = vetor

In [24]:
matriz

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

Mudando a forma do tensor com .reshape

In [26]:
vetor = np.array([1,2,3,4,5,6,7,8,9])
vetor = vetor.reshape(3,3)
vetor

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

A função reshape aceita o uso de -1 como dimensão na especificação do shape. Neste caso, a função reshape determinará automaticamente o número de elementos em cada dimensão de forma a manter inalterado o número total de elementos no tensor. No exemplo abaixo, especificamos o tamanho da primeira dimensão como igual a 2. A função reshape então determinará automaticamente qual o tamanho da segunda dimensão.

In [31]:
vetor = np.array([9,8,7,6,5,4,3,2,1,0])

In [32]:
vetor1 = vetor.reshape(2,-1)
vetor1

array([[9, 8, 7, 6, 5],
       [4, 3, 2, 1, 0]])

In [33]:
vetor2 = vetor.reshape(-1,2)
vetor2

array([[9, 8],
       [7, 6],
       [5, 4],
       [3, 2],
       [1, 0]])

In [40]:
vetor3 = vetor.reshape(-1,1)
vetor3

array([[9],
       [8],
       [7],
       [6],
       [5],
       [4],
       [3],
       [2],
       [1],
       [0]])

### 2.3 Dimensões e total de elementos de um tensor

In [56]:
vetor = np.array(range(54)).reshape(2,3,3,3)

In [57]:
print('Shape = ', vetor.shape)
print('Número de dimensões = ', vetor.ndim)
print('Número de elementos = ', vetor.size)
print('Tensor v = \n', vetor)

Shape =  (2, 3, 3, 3)
Número de dimensões =  4
Número de elementos =  54
Tensor v = 
 [[[[ 0  1  2]
   [ 3  4  5]
   [ 6  7  8]]

  [[ 9 10 11]
   [12 13 14]
   [15 16 17]]

  [[18 19 20]
   [21 22 23]
   [24 25 26]]]


 [[[27 28 29]
   [30 31 32]
   [33 34 35]]

  [[36 37 38]
   [39 40 41]
   [42 43 44]]

  [[45 46 47]
   [48 49 50]
   [51 52 53]]]]


### 2.4 Criando tensores com zeros, ones e diag

In [58]:
V = np.zeros((3,3))
print('V = \n', V)
U = np.ones((3,3))
print('U = \n', U)
D = np.diag([10, 10, 10])
print('D = \n', D)

V = 
 [[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
U = 
 [[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
D = 
 [[10  0  0]
 [ 0 10  0]
 [ 0  0 10]]


### 2.5  Criação de sequências como tensores NumPy

In [61]:
'''Cria um arranjo contendo uma seqüência de valores especificados em um 
intervalo com início e fim dados, espaçados de maneira uniforme'''
v = np.arange(0, 5, 0.5)
print("v =", v)


'''permite definir quantos valores você obtém, incluindo o valor 
mínimo e máximo especificado. Ele infere o tamanho do passo'''
u = np.linspace(0, 5, 10)
print("u =", u)

v = [0.  0.5 1.  1.5 2.  2.5 3.  3.5 4.  4.5]
u = [0.         0.55555556 1.11111111 1.66666667 2.22222222 2.77777778
 3.33333333 3.88888889 4.44444444 5.        ]


## 3. Fontes

* (1) [Numpy Arange](http://pyscience-brasil.wikidot.com/docitem:numpy-arange#:~:text=A%20fun%C3%A7%C3%A3o%20arange%20cria%20um,num%C3%A9rico%2C%20especificado%20pelo%20argumento%20dtype.)
* (2) [Numpy Linspace](http://pyscience-brasil.wikidot.com/docitem:numpy-linspace)
* (3) [Introdução ao Numerical Python (Numpy)](http://www.opl.ufc.br/post/numpy/)